### ISSUE TITLE
Finalize lobby structure for servers

### ISSUE THREAD

**Issue by mhorger3** [jzlotek/drexel-cs451#5]
Need team input on what data structure is appropriate.

Right now:
ArrayList<Player> players
GameState status
boolean visibility

**Comment by jzlotek** [comment]
Player implements Serializable
Move implements Serializable

Need to standardize what a move is and how the game is going to be organized.

I have put a UUID on each piece so we can do a lookup and remove on the renderer

We can either send the serialized move over the socket or we can send it as JSON

Need a move validator as well

Just some of my thoughts so far
